apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  namespace: kafka-monitor
  name: kafka-monitor
  labels:
    app: kafka-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-monitor
  template:
    metadata:
      labels:
        app: kafka-monitor
    spec:
      containers:
      - name: kafka-monitor
        image: danielcoman/kafka-monitor:latest
        imagePullPolicy: Always
        env:
        - name: TEST_TOPIC
          value: "kafka-monitor-1"
        - name: KAFKA_PRODUCE_ZK
          value: "zookeeper.kafka-source.svc.cluster.local:2181"
        - name: KAFKA_PRODUCE_BROKER
          value: "broker.kafka-source.svc.cluster.local:9092"
        - name: KAFKA_CONSUME_ZK
          value: "zookeeper.kafka-destination.svc.cluster.local:2181"
        - name: KAFKA_CONSUME_BROKER
          value: "broker.kafka-destination.svc.cluster.local:9092"
        - name: REPORTER_CLASS
          value: "com.linkedin.kmf.services.GraphiteMetricsReporterService"
        # - name: REPORTER_CLASS
        #   value: "com.linkedin.kmf.services.DefaultMetricsReporterService"
        - name: REPORTER_GRAPHITE_HOST
          value: "prometheus-graphite-exporter.monitoring.svc.cluster.local"
        - name: REPORTER_GRAPHITE_PORT
          value: "9109"
        - name: REPORTER_GRAPHITE_PREFIX
          value: "km"
        - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
          value: "km"
